# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rootstrap Swift Style Guide
description: > # > means to ignore newlines until the next unindented line
  Roostrap's Swift style guid based on Google's swift style guide
timezone: America/Los_Angeles
baseurl: "/swift"
url: "https://rootstrap.github.io/swift"

exclude: [config.ru, Gemfile, Gemfile.lock, Procfile, vendor, README.md]

# Build settings
markdown: kramdown

kramdown:
    syntax_highlighter: rouge

sass:
    style: compressed
    sass_dir: _sass

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      include_in_navigation: true
