#if !canImport(ObjectiveC)
import XCTest

extension AccessorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AccessorTests = [
        ("testBasicAccessors", testBasicAccessors),
        ("testEmptyAccessorBody", testEmptyAccessorBody),
        ("testEmptyAccessorBodyWithComment", testEmptyAccessorBodyWithComment),
        ("testEmptyAccessorList", testEmptyAccessorList),
        ("testSetModifier", testSetModifier),
    ]
}

extension ArrayDeclTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayDeclTests = [
        ("testArrayOfFunctions", testArrayOfFunctions),
        ("testBasicArrays", testBasicArrays),
    ]
}

extension AsExprTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AsExprTests = [
        ("testWithoutPunctuation", testWithoutPunctuation),
        ("testWithPunctuation", testWithPunctuation),
    ]
}

extension AttributeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AttributeTests = [
        ("testAttributeParamSpacing", testAttributeParamSpacing),
    ]
}

extension AvailabilityConditionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AvailabilityConditionTests = [
        ("testAvailabilityCondition", testAvailabilityCondition),
        ("testAvailabilityConditionWithTrailingComment", testAvailabilityConditionWithTrailingComment),
    ]
}

extension BacktickTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BacktickTests = [
        ("testBackticks", testBackticks),
    ]
}

extension ClassDeclTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClassDeclTests = [
        ("testBasicClassDeclarations", testBasicClassDeclarations),
        ("testClassAttributes", testClassAttributes),
        ("testClassFullWrap", testClassFullWrap),
        ("testClassInheritence", testClassInheritence),
        ("testClassWhereClause", testClassWhereClause),
        ("testClassWhereClauseWithInheritence", testClassWhereClauseWithInheritence),
        ("testEmptyClass", testEmptyClass),
        ("testEmptyClassWithComment", testEmptyClassWithComment),
        ("testGenericClassDeclarations", testGenericClassDeclarations),
        ("testOneMemberClass", testOneMemberClass),
    ]
}

extension ClosureExprTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClosureExprTests = [
        ("testArrayClosures", testArrayClosures),
        ("testBasicFunctionClosures", testBasicFunctionClosures),
        ("testBodilessClosure", testBodilessClosure),
        ("testClosureCapture", testClosureCapture),
        ("testClosuresWithIfs", testClosuresWithIfs),
        ("testTrailingClosure", testTrailingClosure),
    ]
}

extension CommentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommentTests = [
        ("testBlockComments", testBlockComments),
        ("testContainerLineComments", testContainerLineComments),
        ("testDocumentationBlockComments", testDocumentationBlockComments),
        ("testDocumentationComments", testDocumentationComments),
        ("testDoesNotInsertExtraNewlinesAfterTrailingComments", testDoesNotInsertExtraNewlinesAfterTrailingComments),
        ("testLineComments", testLineComments),
    ]
}

extension DeinitializerDeclTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeinitializerDeclTests = [
        ("testBasicDeinitializerDeclarations", testBasicDeinitializerDeclarations),
        ("testDeinitializerAttributes", testDeinitializerAttributes),
        ("testEmptyDeinitializer", testEmptyDeinitializer),
    ]
}

extension DictionaryDeclTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DictionaryDeclTests = [
        ("testBasicDictionaries", testBasicDictionaries),
    ]
}

extension EnumDeclTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnumDeclTests = [
        ("testBasicEnumDeclarations", testBasicEnumDeclarations),
        ("testEmptyEnum", testEmptyEnum),
        ("testEmptyEnumWithComment", testEmptyEnumWithComment),
        ("testEnumAttributes", testEnumAttributes),
        ("testEnumFullWrap", testEnumFullWrap),
        ("testEnumInheritence", testEnumInheritence),
        ("testEnumWhereClause", testEnumWhereClause),
        ("testEnumWhereClauseWithInheritence", testEnumWhereClauseWithInheritence),
        ("testGenericEnumDeclarations", testGenericEnumDeclarations),
        ("testIndirectEnum", testIndirectEnum),
        ("testMixedEnumCaseStyles", testMixedEnumCaseStyles),
        ("testOneMemberEnum", testOneMemberEnum),
    ]
}

extension ExtensionDeclTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtensionDeclTests = [
        ("testBasicExtensionDeclarations", testBasicExtensionDeclarations),
        ("testEmptyExtension", testEmptyExtension),
        ("testEmptyExtensionWithComment", testEmptyExtensionWithComment),
        ("testExtensionAttributes", testExtensionAttributes),
        ("testExtensionFullWrap", testExtensionFullWrap),
        ("testExtensionInheritence", testExtensionInheritence),
        ("testExtensionWhereClause", testExtensionWhereClause),
        ("testExtensionWhereClauseWithInheritence", testExtensionWhereClauseWithInheritence),
        ("testOneMemberExtension", testOneMemberExtension),
    ]
}

extension ForInStmtTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ForInStmtTests = [
        ("testBasicForLoop", testBasicForLoop),
        ("testForLabels", testForLabels),
        ("testForLoopFullWrap", testForLoopFullWrap),
        ("testForWhereLoop", testForWhereLoop),
        ("testForWithRanges", testForWithRanges),
    ]
}

extension FunctionCallTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FunctionCallTests = [
        ("testBasicFunctionCalls", testBasicFunctionCalls),
        ("testDiscretionaryLineBreakBeforeClosingParenthesis", testDiscretionaryLineBreakBeforeClosingParenthesis),
        ("testDiscretionaryLineBreaksAreSelfCorrecting", testDiscretionaryLineBreaksAreSelfCorrecting),
    ]
}

extension FunctionDeclTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FunctionDeclTests = [
        ("testAttributedTypes", testAttributedTypes),
        ("testBasicFunctionDeclarations", testBasicFunctionDeclarations),
        ("testBodilessFunctionDecl", testBodilessFunctionDecl),
        ("testBreaksBeforeOrInsideOutput", testBreaksBeforeOrInsideOutput),
        ("testBreaksBeforeOrInsideOutputWithAttributes", testBreaksBeforeOrInsideOutputWithAttributes),
        ("testBreaksBeforeOrInsideOutputWithWhereClause", testBreaksBeforeOrInsideOutputWithWhereClause),
        ("testEmptyFunction", testEmptyFunction),
        ("testFunctionAttributes", testFunctionAttributes),
        ("testFunctionDeclReturns", testFunctionDeclReturns),
        ("testFunctionDeclThrows", testFunctionDeclThrows),
        ("testFunctionFullWrap", testFunctionFullWrap),
        ("testFunctionGenericParameters", testFunctionGenericParameters),
        ("testFunctionWhereClause", testFunctionWhereClause),
        ("testFunctionWithDefer", testFunctionWithDefer),
        ("testOperatorOverloads", testOperatorOverloads),
        ("testRemovesLineBreakBeforeOpenBraceUnlessAbsolutelyNecessary", testRemovesLineBreakBeforeOpenBraceUnlessAbsolutelyNecessary),
    ]
}

extension FunctionTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FunctionTypeTests = [
        ("testFunctionType", testFunctionType),
        ("testFunctionTypeThrows", testFunctionTypeThrows),
    ]
}

extension GuardStmtTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GuardStmtTests = [
        ("testGuardStatement", testGuardStatement),
    ]
}

extension IfConfigTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IfConfigTests = [
        ("testBasicIfConfig", testBasicIfConfig),
    ]
}

extension IfStmtTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IfStmtTests = [
        ("testIfElseStatement", testIfElseStatement),
        ("testIfStatement", testIfStatement),
        ("testMatchingPatternConditions", testMatchingPatternConditions),
    ]
}

extension ImportTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImportTests = [
        ("testImports", testImports),
    ]
}

extension InitializerDeclTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InitializerDeclTests = [
        ("testBasicInitializerDeclarations", testBasicInitializerDeclarations),
        ("testEmptyInitializer", testEmptyInitializer),
        ("testInitializerAttributes", testInitializerAttributes),
        ("testInitializerDeclThrows", testInitializerDeclThrows),
        ("testInitializerFullWrap", testInitializerFullWrap),
        ("testInitializerGenericParameters", testInitializerGenericParameters),
        ("testInitializerOptionality", testInitializerOptionality),
        ("testInitializerWhereClause", testInitializerWhereClause),
    ]
}

extension NewlineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NewlineTests = [
        ("testLeadingNewlines", testLeadingNewlines),
        ("testLeadingNewlinesWithComments", testLeadingNewlinesWithComments),
        ("testTrailingNewlines", testTrailingNewlines),
        ("testTrailingNewlinesWithComments", testTrailingNewlinesWithComments),
    ]
}

extension ProtocolDeclTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProtocolDeclTests = [
        ("testBasicProtocolDeclarations", testBasicProtocolDeclarations),
        ("testEmptyProtocol", testEmptyProtocol),
        ("testEmptyProtocolWithComment", testEmptyProtocolWithComment),
        ("testOneMemberProtocol", testOneMemberProtocol),
        ("testProtocolAttributes", testProtocolAttributes),
        ("testProtocolInheritence", testProtocolInheritence),
        ("testProtocolWithAssociatedtype", testProtocolWithAssociatedtype),
        ("testProtocolWithFunctions", testProtocolWithFunctions),
        ("testProtocolWithInitializers", testProtocolWithInitializers),
    ]
}

extension RepeatStmtTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RepeatStmtTests = [
        ("testBasicRepeatTests", testBasicRepeatTests),
        ("testNestedRepeat", testNestedRepeat),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testStrings", testStrings),
    ]
}

extension StructDeclTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StructDeclTests = [
        ("testBasicStructDeclarations", testBasicStructDeclarations),
        ("testEmptyStruct", testEmptyStruct),
        ("testEmptyStructWithComment", testEmptyStructWithComment),
        ("testGenericStructDeclarations", testGenericStructDeclarations),
        ("testOneMemberStruct", testOneMemberStruct),
        ("testStructAttributes", testStructAttributes),
        ("testStructFullWrap", testStructFullWrap),
        ("testStructInheritence", testStructInheritence),
        ("testStructWhereClause", testStructWhereClause),
        ("testStructWhereClauseWithInheritence", testStructWhereClauseWithInheritence),
    ]
}

extension SubscriptDeclTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubscriptDeclTests = [
        ("testBasicSubscriptDeclarations", testBasicSubscriptDeclarations),
        ("testEmptySubscript", testEmptySubscript),
        ("testSubscriptAttributes", testSubscriptAttributes),
        ("testSubscriptFullWrap", testSubscriptFullWrap),
        ("testSubscriptGenerics", testSubscriptGenerics),
        ("testSubscriptGenericWhere", testSubscriptGenericWhere),
    ]
}

extension SubscriptExprTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubscriptExprTests = [
        ("testBasicSubscriptGetters", testBasicSubscriptGetters),
        ("testBasicSubscriptSetters", testBasicSubscriptSetters),
        ("testSubscriptGettersWithTrailingClosures", testSubscriptGettersWithTrailingClosures),
        ("testSubscriptSettersWithTrailingClosures", testSubscriptSettersWithTrailingClosures),
    ]
}

extension SwitchStmtTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwitchStmtTests = [
        ("testBasicSwitch", testBasicSwitch),
        ("testNestedSwitch", testNestedSwitch),
        ("testSwitchCases", testSwitchCases),
        ("testSwitchCompoundCases", testSwitchCompoundCases),
        ("testSwitchValueBinding", testSwitchValueBinding),
    ]
}

extension TernaryExprTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TernaryExprTests = [
        ("testTernaryExprs", testTernaryExprs),
    ]
}

extension TryCatchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TryCatchTests = [
        ("testBasicTries", testBasicTries),
        ("testCatchWhere", testCatchWhere),
        ("testDoTryCatch", testDoTryCatch),
        ("testNestedDo", testNestedDo),
    ]
}

extension TupleDeclTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TupleDeclTests = [
        ("testBasicTuples", testBasicTuples),
        ("testLabeledTuples", testLabeledTuples),
    ]
}

extension TypeAliasTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TypeAliasTests = [
        ("testTypealias", testTypealias),
        ("testTypealiasAttributes", testTypealiasAttributes),
        ("testTypealiasGenericTests", testTypealiasGenericTests),
    ]
}

extension UnknownDeclTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnknownDeclTests = [
        ("testUnknownDecl", testUnknownDecl),
    ]
}

extension VariableDeclarationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VariableDeclarationTests = [
        ("testBasicVariableDecl", testBasicVariableDecl),
        ("testVariableDeclWithAttributes", testVariableDeclWithAttributes),
    ]
}

extension WhileStmtTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WhileStmtTests = [
        ("testBasicWhileLoops", testBasicWhileLoops),
        ("testLabeledWhileLoops", testLabeledWhileLoops),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AccessorTests.__allTests__AccessorTests),
        testCase(ArrayDeclTests.__allTests__ArrayDeclTests),
        testCase(AsExprTests.__allTests__AsExprTests),
        testCase(AttributeTests.__allTests__AttributeTests),
        testCase(AvailabilityConditionTests.__allTests__AvailabilityConditionTests),
        testCase(BacktickTests.__allTests__BacktickTests),
        testCase(ClassDeclTests.__allTests__ClassDeclTests),
        testCase(ClosureExprTests.__allTests__ClosureExprTests),
        testCase(CommentTests.__allTests__CommentTests),
        testCase(DeinitializerDeclTests.__allTests__DeinitializerDeclTests),
        testCase(DictionaryDeclTests.__allTests__DictionaryDeclTests),
        testCase(EnumDeclTests.__allTests__EnumDeclTests),
        testCase(ExtensionDeclTests.__allTests__ExtensionDeclTests),
        testCase(ForInStmtTests.__allTests__ForInStmtTests),
        testCase(FunctionCallTests.__allTests__FunctionCallTests),
        testCase(FunctionDeclTests.__allTests__FunctionDeclTests),
        testCase(FunctionTypeTests.__allTests__FunctionTypeTests),
        testCase(GuardStmtTests.__allTests__GuardStmtTests),
        testCase(IfConfigTests.__allTests__IfConfigTests),
        testCase(IfStmtTests.__allTests__IfStmtTests),
        testCase(ImportTests.__allTests__ImportTests),
        testCase(InitializerDeclTests.__allTests__InitializerDeclTests),
        testCase(NewlineTests.__allTests__NewlineTests),
        testCase(ProtocolDeclTests.__allTests__ProtocolDeclTests),
        testCase(RepeatStmtTests.__allTests__RepeatStmtTests),
        testCase(StringTests.__allTests__StringTests),
        testCase(StructDeclTests.__allTests__StructDeclTests),
        testCase(SubscriptDeclTests.__allTests__SubscriptDeclTests),
        testCase(SubscriptExprTests.__allTests__SubscriptExprTests),
        testCase(SwitchStmtTests.__allTests__SwitchStmtTests),
        testCase(TernaryExprTests.__allTests__TernaryExprTests),
        testCase(TryCatchTests.__allTests__TryCatchTests),
        testCase(TupleDeclTests.__allTests__TupleDeclTests),
        testCase(TypeAliasTests.__allTests__TypeAliasTests),
        testCase(UnknownDeclTests.__allTests__UnknownDeclTests),
        testCase(VariableDeclarationTests.__allTests__VariableDeclarationTests),
        testCase(WhileStmtTests.__allTests__WhileStmtTests),
    ]
}
#endif
